#!/bin/sh
set -eu

link_dotfiles() {
    echo '> creating essential dirs'
    mkdir -p "${XDG_CONFIG_HOME:-"$HOME/.config"}"

    echo '> linking dotfiles'
    ln -sfn $(pwd)/nvim ~/.config/nvim
    ln -sfn $(pwd)/.zshrc ~/.zshrc
    ln -sfn $(pwd)/.gitignore ~/.gitignore
    ln -sfn $(pwd)/.psqlrc ~/.psqlrc
}

setup_linux() {
    echo '> installing essential packages'
    sudo apt-get update && sudo apt-get install -y curl git zsh neovim tree ncdu htop ripgrep jq
}

setup_mac() {
    xcode-select -p >/dev/null 2>&1 || { echo '> installing command line tools for xcode'; xcode-select --install; }
    command -v brew >/dev/null 2>&1 || {
        echo '> installing homebrew'
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        eval "$(/opt/homebrew/bin/brew shellenv)"
    }
    echo '> installing essential packages'
    brew update && brew install watch neovim tree ncdu htop ripgrep jq font-ubuntu-sans-mono
}

config_git() {
    echo '> configuring git'
    git config --global core.excludesFile ~/.gitignore
    git config --global push.autoSetupRemote true
    git config --global pull.rebase true
    git config --global diff.tool nvimdiff
    git config --global merge.tool nvimdiff
    git config --global mergetool.keepBackup false

    echo '> downloading git-prompt'
    curl -fsSL https://raw.githubusercontent.com/git/git/refs/heads/master/contrib/completion/git-prompt.sh -o ~/.git-prompt.sh
}

config_shell() {
    [ "${SHELL##*/}" = zsh ] && { echo '* default shell is already zsh'; return 0; }
    zsh_path=$(command -v zsh || true)
    [ -n "$zsh_path" ] || { echo '! zsh not found in path' >&2; return 1; }

    echo '> changing default shell to zsh'
    grep -qxF "$zsh_path" /etc/shells || echo "$zsh_path" | sudo tee -a /etc/shells
    chsh -s "$zsh_path"
    echo '* please log out and log back in for shell change to take effect'
}

main() {
    link_dotfiles
    case $(uname -s) in
        Linux)  setup_linux ;;
        Darwin) setup_mac ;;
        *)      echo '! unsupported os: only linux and mac' >&2; exit 1 ;;
    esac
    config_git
    config_shell
}

main "$@"
# vim: ft=sh
