vim9script
set nocompatible noswapfile nobackup
set autoindent shiftround smartindent nomodeline
set showmatch ruler title visualbell autoread
set ignorecase smartcase hlsearch incsearch
set shiftwidth=4 tabstop=4 softtabstop=4 expandtab
set wildoptions=pum,tagfile,fuzzy wildcharm=<C-z>
set list listchars=tab:>\ ,trail:-,nbsp:+
&showbreak = '+++ '
filetype plugin on
filetype indent on
syntax enable

# extend find with git-ls-files
def g:FuzzyFind(cmdarg: string, cmdcomplete: bool): list<string>
  var result = systemlist('git ls-files --cached --others --exclude-standard 2>/dev/null')
  if v:shell_error != 0
    result = systemlist('find . -type f')
  endif
  return empty(cmdarg) ? result : matchfuzzy(result, cmdarg)
enddef
set findfunc=g:FuzzyFind
nnoremap <Space>f :find 
nnoremap <Space>F :find <C-r><C-w><C-z>

# grep/git-grep recursive by default
system('git rev-parse --is-inside-work-tree &>/dev/null')
&grepprg = v:shell_error != 0 ? 'grep -rn $*' : 'git grep -n $*'
nnoremap <Space>g :grep! -i ''<Left>
vnoremap <Space>g "0y:grep! '<C-r>0'<Left>
nnoremap <Space>G :grep! '<C-r><C-w>'<CR>

# terminal emulators historically map C-Space to the null byte
# (\0, ASCII 0) which VIM represents as <NUL>
nnoremap <Nul> :ls t<CR>:buffer 
nnoremap - :edit %:.:h<C-z><C-z>

# redraw + clear search highlight
nnoremap <C-l> <Cmd>noh<Bar>dif<Bar>redr!<CR>
g:netrw_dirhistmax = 0 # zero to suppress history

# clipboard
# all motions work the same as normal [y]
nnoremap <C-w>y "+y
vnoremap <C-w>y "+y
nnoremap <C-w>p "+p
vnoremap <C-w>p "+p
nnoremap <C-w>P "+P

autocmd BufNewFile,BufRead *.log* setf messages
autocmd BufNewFile,BufRead *.psql setf sql
autocmd BufNewFile,BufRead *.mdc  setf markdown
autocmd FileType help,qf nnoremap <buffer> q <Cmd>bd<CR>
autocmd TerminalWinOpen * nnoremap <buffer> q <Cmd>bd!<CR>
autocmd QuickFixCmdPost [^l]* cwindow

# LOCAL-specific
set autocomplete number updatetime=512
set completeopt+=fuzzy sessionoptions-=options
&undodir = $'{$XDG_STATE_HOME}/vim/undo'
if !isdirectory(&undodir) | mkdir(&undodir, 'p') | endif
set undofile cursorline laststatus=2 background=dark
colorscheme retrobox

# sessionize
source <sfile>:h/utils/session.vim
command! Blame {
  const start = max([line('.') - 2, 1])
  const finish = start + 9
  execute $'!git blame -L {start},{finish} {shellescape(expand("%"))}'
}

# useful packages
packadd comment
packadd hlyank
g:hlyank_duration = 128

# keep things simple here, only essentials
# plugins are managed as git submodules under vim/pack/plugins/opt
packadd signify
packadd undotree
nnoremap <C-w>u <Cmd>UndotreeToggle<CR>
source <sfile>:h/utils/lsp.vim
defcompile
