vim9script
set nocompatible encoding=utf-8 fileencoding=utf-8
set noswapfile nobackup nomodeline nrformats=bin,hex
set showmatch ruler title visualbell autoread
set ignorecase smartcase hlsearch incsearch
set shiftwidth=2 tabstop=2 expandtab shiftround
set wildoptions=pum,tagfile,fuzzy wildcharm=<C-z>
set list listchars=tab:>\ ,trail:-,nbsp:+
&showbreak = '+++ '
filetype plugin on
filetype indent on
syntax enable

&grepprg = 'git grep -n $*'
var find_cmd = 'git ls-files --cached --others --exclude-standard 2>/dev/null'
system('git rev-parse --is-inside-work-tree &>/dev/null')
if v:shell_error != 0
  find_cmd = 'find . -type f'
  &grepprg = 'grep -rn $*'
endif # when not in a git repo

# :find command should search files
def g:FindFiles(cmd_arg: string, _cmd_comp: bool): list<string>
  var out = systemlist(find_cmd)
  if v:shell_error != 0 | return [] | endif
  return empty(cmd_arg) ? out : matchfuzzy(out, cmd_arg)
enddef
set findfunc=g:FindFiles
# !intentional trailing space below!
nnoremap <Space>f :find 
nnoremap <Space>F :find <C-r><C-w>

# :grep recursive within cwd by default
nnoremap <Space>g :grep! -i ''<Left>
vnoremap <Space>g "0y:grep! '<C-r>0'<Left>
nnoremap <Space>G :grep! '<C-r><C-w>'<CR>

# terminal emulators historically map <C-Space> to the ASCII NUL (0x00, \0)
# which VIM represents as <Nul> or ^@ in buffers - this occurs because
# <C-Space> behaves as ^@ in many terminal emulators, sending a single zero byte
nnoremap <Nul> :ls t<CR>:buffer 
# !intentional trailing space  ^!
nnoremap - :edit %:.:h<C-z><C-z>

# redraw + clear search highlight
nnoremap <C-l> <Cmd>noh<Bar>dif<Bar>redr!<CR>
g:netrw_dirhistmax = 0 # zero to suppress history

# moving in command mode
cnoremap <C-a> <Home>
cnoremap <C-e> <End>
cnoremap <C-f> <Right>
cnoremap <C-b> <Left>

# yank/paste to/from system clipboard
# all motions work the same as normal [y]
nnoremap <C-w>y "+y
vnoremap <C-w>y "+y
nnoremap <C-w>p "+p
vnoremap <C-w>p "+p
nnoremap <C-w>P "+P

autocmd QuickFixCmdPost [^l]* cwindow
autocmd BufNewFile,BufRead *.log* setf messages
autocmd BufNewFile,BufRead *.psql setf sql
autocmd FileType help,qf nnoremap <buffer> q <Cmd>bd<CR>
autocmd FileType sh,bash,zsh setl shiftwidth=4 tabstop=4

# LOCAL-specific config
set autoindent smartindent autocomplete
set completeopt+=fuzzy sessionoptions-=options
&undodir = $'{$XDG_STATE_HOME}/vim/undo'
if !isdirectory(&undodir) | mkdir(&undodir, 'p') | endif
set undofile background=dark updatetime=512

# sessionize
source <sfile>:h/utils/session.vim
command! Blame {
  const start = max([line('.') - 2, 1])
  const end = start + 9
  execute $'!git blame -L {start},{end} {shellescape(expand("%"))}'
} # show what revision and author of the last modified

# useful optional packages
packadd comment
packadd hlyank
g:hlyank_duration = 128
packadd! editorconfig # need to be loaded during startup

# keep things simple here, only essentials
# plugins are managed as git submodules under vim/pack/plugins/opt
source <sfile>:h/utils/lsp.vim
defcompile
